version: "3.9"
services:
  # Frontend service
  frontend:
    container_name: flight-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  # Backend service
  backend:
    container_name: flight-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres.enazhbswgifqltwawujh:8CyrvMv8dlVFj6HQ@aws-0-eu-north-1.pooler.supabase.com:5432/postgres
      - SECRET_KEY=8CyrvMv8dlVFj6HQ
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules


